<?php

require_once 'site_audit.autoload.inc';
require_once 'Report/Abstract.php';
require_once 'Check/Abstract.php';

/**
 * Implements hook_menu().
 *
 * @return array
 */
function site_audit_menu() {
  $items['admin/reports/site-audit'] = [
    'title' => 'Site Audit',
    'description' => 'View the site audit report for this site.',
    'page callback' => 'site_audit_report',
    'access arguments' => ['administer site configuration'],
    'type' => MENU_NORMAL_ITEM,
  ];
  $items['admin/reports/site-audit/view'] = [
    'title' => 'Report',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  ];
  $items['admin/reports/site-audit/configuration'] = [
    'title' => 'Settings',
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['site_audit_settings_form'],
    'access arguments' => ['administer site configuration'],
    'type' => MENU_LOCAL_TASK,
  ];
  return $items;
}

/**
 * Implements hook_config_info().
 */
function site_audit_config_info() {
  $prefixes['site_audit.settings'] = array(
    'label' => t('Site Audit settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Renders Site Audit Settings form.
 * @param $form
 * @param $form_state
 * @return array
 */
function site_audit_settings_form($form, &$form_state) {
  $config = config('site_audit.settings');
  backdrop_set_title(t('Site Audit Settings'));
  $reports = site_audit_get_web_reports();
  $form['#config'] = 'site_audit.settings';
  $form['site_audit_reports'] = [
    '#title' => t('Site Audit Reports'),
    '#description' => t('Select the reports to show on the Site Audit Report page. If none are selected, all reports will be included.'),
    '#type' => 'select',
    '#multiple' => TRUE,
    '#options' => $reports,
    '#default_value' => $config->get('site_audit_reports'),
  ];

  $form['site_audit_pagespeed_url'] = array(
    '#title' => t('Google Pagespeed Test URL'),
    '#description' => t("To receive reports from Google's PageSpeed service, enter a URL to test here. To skip reporting, leave this blank. WARNING: This will greatly increase the time to generate the report."),
    '#type' => 'textfield',
    '#default_value' => $config->get('site_audit_pagespeed_url'),
  );
  $form['site_audit_pagespeed_api_key'] = array(
    '#title' => t('Google Pagespeed API Key'),
    '#description' => t("To receive reports from Google's PageSpeed service, enter an API key here. See !link for more information.", array(
      '!link' => l('https://developers.google.com/speed/docs/insights/v1/getting_started#auth', 'https://developers.google.com/speed/docs/insights/v1/getting_started#auth'),
    )),
    '#type' => 'textfield',
    '#default_value' => $config->get('site_audit_pagespeed_api_key'),
  );

  return system_settings_form($form);
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function site_audit_get_web_reports() {
  $reports = file_scan_directory(__dir__ . '/Report', '/\.php/');
  $supported_reports = [];
  $invalid_reports = [
    'Abstract'
  ];
  foreach ($reports as $report_class) {
    if ($report_class->name && !in_array($report_class->name, $invalid_reports)) {
      $supported_reports[$report_class->name] = $report_class->name;
    }
  }
  return $supported_reports;
}


/**
 * Menu callback for the report page UI.
 *
 * @return array
 */
function site_audit_report() {
  $output = [];
  $reports = config_get('site_audit.settings', 'site_audit_reports') ? : site_audit_get_web_reports();

  foreach ($reports as $report_class) {
    $class_name = "SiteAuditReport" . $report_class;
    $output['reports']['#items'][] = "$class_name Report";
    $report = new $class_name();
    $output[$report_class] = [
      '#markup' => $report->toHtml(),
    ];
  }

  return $output;
}

// We've tried to convert drush only reports to web based reports without altering the original report classes, by wrapping
// the drush functions used and mirroring the expect return values.

if (!function_exists('dt')) {
  function dt($text, $args = [], $options = []) {
    return t($text, $args, $options);
  }
}
//
//if (!function_exists('drush_get_option')) {
//  function drush_get_option($key, $default = NULL ) {
//    switch ($key) {
//      case 'html':
//      case 'detail':
//        return TRUE;
//      case 'json':
//      case 'skip':
//      case 'bootstrap':
//      case 'vendor':
//      case 'extension_count':
//      case 'impact':
//      case 'limit':
//      case 'min_rows':
//      default :
//        return FALSE;
//    }
//  }
//}
//
//if (!function_exists('drush_get_commands')) {
//  function drush_get_commands() {
//    $commands = [];
//    // TODO: Generate these by scanning the Check directory.
//    $commands['audit_best_practices']['checks'] = ['Multisite', 'Settings', 'SitesDefault', 'SitesAll', 'SitesSuperfluous', 'Fast404', 'PhpFilter'];
//    $commands['audit_block']['checks'] = ['Enabled', 'Cache', 'CacheReport'];
//    $commands['audit_cache']['checks'] = ['Anon', 'Lifetime', 'PageExpire', 'PageCompression', 'PreprocessCss', 'PreprocessJs', 'Lock', 'Backends', 'DefaultClass', 'Bins'];
//    $commands['audit_codebase']['checks'] = ['SizeFiles', 'SizeAll', 'ManagedFileCount', 'ManagedFileSize'];
//    $commands['audit_content']['checks'] = ['ContentTypes', 'ContentTypesUnused', 'DuplicateTitles', 'Vocabularies', 'VocabulariesUnused', 'FieldEnabled', 'FieldCount', 'FieldInstances', 'FieldsUnused'];
//    $commands['audit_cron']['checks'] = ['Enabled', 'Running', 'Last'];
//    $commands['audit_database']['checks'] = ['Size', 'RowCount', 'Collation', 'Engine'];
//    $commands['audit_extensions']['checks'] = ['Count', 'Dev', 'Unrecommended', 'Redundant', 'Duplicate', 'Missing', 'Disabled', 'Update', 'Security'];
//    $commands['audit_insights']['checks'] = ['Analyze'];
//    $commands['audit_security']['checks'] = ['MenuRouter'];
//    $commands['audit_status']['checks'] = ['System'];
//    $commands['audit_users']['checks'] = ['CountAll', 'CountBlocked', 'WhoIsNumberOne', 'BlockedNumberOne'];
//    $commands['audit_views']['checks'] = ['Enabled', 'Count', 'CacheResults', 'CacheOutput'];
//    $commands['audit_watchdog']['checks'] = ['Syslog', 'Enabled', 'Count', 'Age', '404', 'Php'];
//    return $commands;
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('drush_get_extensions')) {
//  function drush_get_extensions($include_core = FALSE) {
//    $enabledModules = module_list();
//    $enabledThemes = list_themes();
//    $enabledExtensions = array_merge($enabledModules, $enabledThemes);
//    return $enabledExtensions;
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('drush_get_extension_status')) {
//  function drush_get_extension_status($extension) {
//    return module_exists($extension) ? 'enabled' : 'disabled';
//  }
//}
//if (!defined('DRUSH_COMMAND') && !function_exists('drush_parse_command')) {
//  function drush_parse_command() {
//    return ['command' => 'audit_all'];
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('drush_command_invoke_all_ref')) {
//  function drush_command_invoke_all_ref($hook, &$ref = NULL) {
//    return [];
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('drush_set_error')) {
//  function drush_set_error($message, $type = NULL) {
//    backdrop_set_message($message);
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('drush_get_context')) {
//  function drush_get_context($var) {
//    return __DIR__;
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('drush_invoke_process')) {
//  function drush_invoke_process() {
//    return [];
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('site_audit_env_is_dev')) {
//  function site_audit_env_is_dev() {
//    return FALSE;
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('core_watchdog_query')) {
//  function core_watchdog_query() {
//    return FALSE;
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('drush_db_select')) {
//  function drush_db_select() {
//    return FALSE;
//  }
//}
//
//if (!defined('DRUSH_COMMAND') && !function_exists('drush_db_fetch_object')) {
//  function drush_db_fetch_object() {
//    return FALSE;
//  }
//}
//
//if (!!defined('DRUSH_COMMAND') && !function_exists('_drush_sql_get_db_spec')) {
//  function _drush_sql_get_db_spec() {
//    return FALSE;
//  }
//}

/**
 * Determine if in a development environment.
 *
 * @todo This only ever worked on pantheon. Let's deprecate it.
 *
 * @deprecated
 * @return bool
 *   Whether site is in a development environment.
 */
function site_audit_env_is_dev() {
  return FALSE;
}

/**
 * Implements hook_autoload_info().
 */
function site_audit_autoload_info() {
  return array(
    'SiteAuditCheckAbstract' => 'Check/Abstract.php',
    'SiteAuditCheckBestPracticesFast404' => 'Check/BestPractices/Fast404.php',
    'SiteAuditCheckBestPracticesMultisite' => 'Check/BestPractices/Multisite.php',
    'SiteAuditCheckBestPracticesPhpFilter' => 'Check/BestPractices/PhpFilter.php',
    'SiteAuditCheckBestPracticesSettings' => 'Check/BestPractices/Settings.php',
    'SiteAuditCheckBestPracticesSitesAll' => 'Check/BestPractices/SitesAll.php',
    'SiteAuditCheckBestPracticesSitesDefault' => 'Check/BestPractices/SitesDefault.php',
    'SiteAuditCheckBestPracticesSitesSuperfluous' => 'Check/BestPractices/SitesSuperfluous.php',
    'SiteAuditCheckBlockCache' => 'Check/Block/Cache.php',
    'SiteAuditCheckBlockCacheReport' => 'Check/Block/CacheReport.php',
    'SiteAuditCheckBlockEnabled' => 'Check/Block/Enabled.php',
    'SiteAuditCheckCacheAnon' => 'Check/Cache/Anon.php',
    'SiteAuditCheckCacheBackends' => 'Check/Cache/Backends.php',
    'SiteAuditCheckCacheBins' => 'Check/Cache/Bins.php',
    'SiteAuditCheckCacheDefaultClass' => 'Check/Cache/DefaultClass.php',
    'SiteAuditCheckCacheLifetime' => 'Check/Cache/Lifetime.php',
    'SiteAuditCheckCacheLock' => 'Check/Cache/Lock.php',
    'SiteAuditCheckCachePageCompression' => 'Check/Cache/PageCompression.php',
    'SiteAuditCheckCachePageExpire' => 'Check/Cache/PageExpire.php',
    'SiteAuditCheckCachePreprocessCss' => 'Check/Cache/PreprocessCss.php',
    'SiteAuditCheckCachePreprocessJs' => 'Check/Cache/PreprocessJs.php',
    'SiteAuditCheckCodebaseManagedFileCount' => 'Check/Codebase/ManagedFileCount.php',
    'SiteAuditCheckCodebaseManagedFileSize' => 'Check/Codebase/ManagedFileSize.php',
    'SiteAuditCheckCodebaseSizeAll' => 'Check/Codebase/SizeAll.php',
    'SiteAuditCheckCodebaseSizeFiles' => 'Check/Codebase/SizeFiles.php',
    'SiteAuditCheckContentContentTypes' => 'Check/Content/ContentTypes.php',
    'SiteAuditCheckContentContentTypesUnused' => 'Check/Content/ContentTypesUnused.php',
    'SiteAuditCheckContentDuplicateTitles' => 'Check/Content/DuplicateTitles.php',
    'SiteAuditCheckContentFieldCount' => 'Check/Content/FieldCount.php',
    'SiteAuditCheckContentFieldEnabled' => 'Check/Content/FieldEnabled.php',
    'SiteAuditCheckContentFieldInstances' => 'Check/Content/FieldInstances.php',
    'SiteAuditCheckContentFieldsUnused' => 'Check/Content/FieldsUnused.php',
    'SiteAuditCheckContentVocabularies' => 'Check/Content/Vocabularies.php',
    'SiteAuditCheckContentVocabulariesUnused' => 'Check/Content/VocabulariesUnused.php',
    'SiteAuditCheckCronEnabled' => 'Check/Cron/Enabled.php',
    'SiteAuditCheckCronLast' => 'Check/Cron/Last.php',
    'SiteAuditCheckCronRunning' => 'Check/Cron/Running.php',
    'SiteAuditCheckDatabaseCollation' => 'Check/Database/Collation.php',
    'SiteAuditCheckDatabaseEngine' => 'Check/Database/Engine.php',
    'SiteAuditCheckDatabaseRowCount' => 'Check/Database/RowCount.php',
    'SiteAuditCheckDatabaseSize' => 'Check/Database/Size.php',
    'SiteAuditCheckExtensionsCount' => 'Check/Extensions/Count.php',
    'SiteAuditCheckExtensionsDev' => 'Check/Extensions/Dev.php',
    'SiteAuditCheckExtensionsDisabled' => 'Check/Extensions/Disabled.php',
    'SiteAuditCheckExtensionsDuplicate' => 'Check/Extensions/Duplicate.php',
    'SiteAuditCheckExtensionsMissing' => 'Check/Extensions/Missing.php',
    'SiteAuditCheckExtensionsRedundant' => 'Check/Extensions/Redundant.php',
    'SiteAuditCheckExtensionsSecurity' => 'Check/Extensions/Security.php',
    'SiteAuditCheckExtensionsUnrecommended' => 'Check/Extensions/Unrecommended.php',
    'SiteAuditCheckExtensionsUpdate' => 'Check/Extensions/Update.php',
    'SiteAuditCheckFrontEndTemplateFiles' => 'Check/FrontEnd/TemplateFiles.php',
    'SiteAuditCheckInsightsAnalyze' => 'Check/Insights/Analyze.php',
    'SiteAuditCheckRolesRolesList' => 'Check/Roles/RolesList.php',
    'SiteAuditCheckRolesRolesPermissions' => 'Check/Roles/RolesPermissions.php',
    'SiteAuditCheckSecurityMenuRouter' => 'Check/Security/MenuRouter.php',
    'SiteAuditCheckStatusSystem' => 'Check/Status/System.php',
    'SiteAuditCheckUsersBlockedNumberOne' => 'Check/Users/BlockedNumberOne.php',
    'SiteAuditCheckUsersCountAll' => 'Check/Users/CountAll.php',
    'SiteAuditCheckUsersCountBlocked' => 'Check/Users/CountBlocked.php',
    'SiteAuditCheckUsersWhoIsNumberOne' => 'Check/Users/WhoIsNumberOne.php',
    'SiteAuditCheckViewsCacheOutput' => 'Check/Views/CacheOutput.php',
    'SiteAuditCheckViewsCacheResults' => 'Check/Views/CacheResults.php',
    'SiteAuditCheckViewsCount' => 'Check/Views/Count.php',
    'SiteAuditCheckViewsEnabled' => 'Check/Views/Enabled.php',
    'SiteAuditCheckWatchdog404' => 'Check/Watchdog/404.php',
    'SiteAuditCheckWatchdogAge' => 'Check/Watchdog/Age.php',
    'SiteAuditCheckWatchdogCount' => 'Check/Watchdog/Count.php',
    'SiteAuditCheckWatchdogEnabled' => 'Check/Watchdog/Enabled.php',
    'SiteAuditCheckWatchdogPhp' => 'Check/Watchdog/Php.php',
    'SiteAuditCheckWatchdogSyslog' => 'Check/Watchdog/Syslog.php',
    'SiteAuditReportAbstract' => 'Report/Abstract.php',
    'SiteAuditReportBestPractices' => 'Report/BestPractices.php',
    'SiteAuditReportBlock' => 'Report/Block.php',
    'SiteAuditReportCache' => 'Report/Cache.php',
    'SiteAuditReportCodebase' => 'Report/Codebase.php',
    'SiteAuditReportContent' => 'Report/Content.php',
    'SiteAuditReportCron' => 'Report/Cron.php',
    'SiteAuditReportDatabase' => 'Report/Database.php',
    'SiteAuditReportExtensions' => 'Report/Extensions.php',
    'SiteAuditReportFrontEnd' => 'Report/FrontEnd.php',
    'SiteAuditReportInsights' => 'Report/Insights.php',
    'SiteAuditReportRoles' => 'Report/Roles.php',
    'SiteAuditReportSecurity' => 'Report/Security.php',
    'SiteAuditReportStatus' => 'Report/Status.php',
    'SiteAuditReportUsers' => 'Report/Users.php',
    'SiteAuditReportViews' => 'Report/Views.php',
    'SiteAuditReportWatchdog' => 'Report/Watchdog.php',
  );
}


